# DDL – Para usar no Data Modeler 

-- Tabela Cliente 

CREATE TABLE Cliente ( 

    ID_Cliente NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 

    Nome VARCHAR2(100) NOT NULL, 

    Email VARCHAR2(100) NOT NULL, 

    Telefone VARCHAR2(15), 

    Data_Nascimento DATE, 

    Endereço VARCHAR2(255) 

); 


-- Tabela Clínica 

CREATE TABLE Clínica ( 

    ID_Clínica NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 

    Nome VARCHAR2(100) NOT NULL, 

    Endereço VARCHAR2(255), 

    Telefone VARCHAR2(15), 

    Avaliação FLOAT, 

    Preço_Médio FLOAT 

); 

  
-- Tabela Consulta 

CREATE TABLE Consulta ( 

    ID_Consulta NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 

    ID_Cliente NUMBER, 

    ID_Clínica NUMBER, 

    Dentista_ID NUMBER, 

    Tipo_Serviço VARCHAR2(100), 

    Data_Consulta DATE, 

    Hora_Consulta DATE, 

    Tipo_Consulta VARCHAR2(50), 

    Local_Consulta VARCHAR2(255), 

    Status_Consulta VARCHAR2(20), 

    Observações VARCHAR2(250),

    Sintomas VARCHAR2(250),

    Tratamento_Recomendado VARCHAR2(250),

    Custo FLOAT, 

    Forma_Pagamento VARCHAR2(50), 

    Prescrição VARCHAR2(250),

    Data_Retorno DATE, 

    FOREIGN KEY (ID_Cliente) REFERENCES Cliente(ID_Cliente), 

    FOREIGN KEY (ID_Clínica) REFERENCES Clínica(ID_Clínica) 

); 

  
-- Tabela Sinistro 

CREATE TABLE Sinistro ( 

    ID_Sinistro NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 

    Nome VARCHAR2(100), 

    Descrição VARCHAR2(250),

    Status_Sinistro VARCHAR2(20), 

    Descricao_Status VARCHAR2(250),

    Valor_Sinistro FLOAT, 

    Data_Abertura DATE, 

    Data_Resolucao DATE, 

    Documentacao VARCHAR2(250), 

); 

  
-- Tabela Feedback 

CREATE TABLE Feedback ( 

    ID_Feedback NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 

    ID_Cliente NUMBER, 

    ID_Clínica NUMBER, 

    Avaliação FLOAT, 

    Comentário VARCHAR2(250),

    FOREIGN KEY (ID_Cliente) REFERENCES Cliente(ID_Cliente), 

    FOREIGN KEY (ID_Clínica) REFERENCES Clínica(ID_Clínica) 

); 

  
-- Tabela Formulário Detalhado 

CREATE TABLE formulario_personalizado_cliente ( 

    formulario_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 

    usuario_id NUMBER, 

    Historico_Familiar VARCHAR2(250),

    Plano_Odontologico VARCHAR2(100), 

    Estado_Civil VARCHAR2(20), 

    Profissao VARCHAR2(100), 

    Renda_Mensal FLOAT, 

    Tempo_Residencia VARCHAR2(50), 

    Historico_Medico VARCHAR2(250),

    Alergias VARCHAR2(250),

    Condicoes_Preexistentes VARCHAR2(250),

    Uso_Medicamentos VARCHAR2(250),

    Familiar_Com_Doencas_Dentarias VARCHAR2(255), 

    Participacao_Em_Programas_Preventivos CHAR(1), -- 'Y' ou 'N' 

    Historico_De_Fraude CHAR(1), -- 'Y' ou 'N' 

    Contatos_Emergenciais VARCHAR2(250), 

    Historico_De_Reclamacoes VARCHAR2(250),

    Participacao_Em_Pesquisas CHAR(1), -- 'Y' ou 'N' 

    Data_Ultima_Atualizacao DATE, 

    Frequencia_Consultas_Periodicas NUMBER, 

    Sinalizacao_De_Risco VARCHAR2(250),

    Data_De_Nascimento_Mae DATE, 

    Data_De_Nascimento_Pai DATE, 

    Historico_De_Viagens VARCHAR2(250),

    Historico_De_Mudancas_De_Endereco VARCHAR2(250),

    Preferencias_De_Contato VARCHAR2(50), 

    Observacoes_Finais VARCHAR2(250),

    FOREIGN KEY (usuario_id) REFERENCES Usuarios(usuario_id) -- Supondo que a tabela Usuarios exista 

); 


CREATE TABLE Agenda ( 

    ID_Agenda NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 

    ID_Cliente NUMBER, 

    ID_Consulta NUMBER, 

    Data_Consulta DATE, 

    Hora_Consulta DATE, 

    Status_Consulta VARCHAR2(20), 

    Observacoes VARCHAR2(250),

    FOREIGN KEY (ID_Cliente) REFERENCES Cliente(ID_Cliente), 

    FOREIGN KEY (ID_Consulta) REFERENCES Consulta(ID_Consulta) 

); 


CREATE TABLE Notificacoes ( 

    ID_Notificacao NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 

    ID_Cliente NUMBER, 

    Tipo_Notificacao VARCHAR2(20), -- 'Email' ou 'WhatsApp' 

    Mensagem VARCHAR2(250), 

    Data_Envio DATE, 

    Status_Notificacao VARCHAR2(20), -- 'Enviada', 'Pendente', 'Falha' 

    FOREIGN KEY (ID_Cliente) REFERENCES Cliente(ID_Cliente) 

); 

 

Aqui estão os pontos que garantem a normalização dentro da terceira forma: 


1. Eliminação de Redundâncias 

Cada tabela representa uma entidade única (Cliente, Clínica, Consulta, Sinistro, Feedback, Formulário Detalhado), evitando a duplicação de informações. 

2. Dependências Funcionais 

Todos os atributos não-chave dependem exclusivamente da chave primária da tabela. Por exemplo: 

Na tabela Consulta, todos os atributos (como Tipo_Serviço, Data_Consulta, etc.) dependem do ID_Consulta. 

Na tabela Cliente, todos os atributos dependem do ID_Cliente. 

3. Atributos Multivalorados 

Não há atributos multivalorados. Cada campo contém apenas um valor por registro. 

4. Transitiva Dependência 

Não existem dependências transitivas. Todos os atributos são diretamente dependentes da chave primária, e não de outros atributos. 

 
